#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
KEY_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/varch-controller"
KEYSTORE="$KEY_DIR/release.p12"
AUR_KEY="$HOME/.ssh/aur_varchd"
_again="" _owner=""

banner "Release pipeline setup for $REPO"

# ── Stage 1: the key that signs every release APK ─────────────────────────
stage "Android signing key"
say "Every release APK must be signed with the same key."
say "Android refuses an update signed with a different one, so this key is for life."
if [[ -f "$KEYSTORE" ]]; then
  note "Found an existing keystore at $KEYSTORE, so it will be reused."
  ask_secret RELEASE_KEYSTORE_PASSWORD "Its password:"
  export RELEASE_KEYSTORE_PASSWORD
else
  step "Pick a password of at least 6 characters and store it in your password manager."
  ask_secret RELEASE_KEYSTORE_PASSWORD "Keystore password:"
  ask_secret _again "Same password again:"
  [[ "$RELEASE_KEYSTORE_PASSWORD" == "$_again" ]] || { warn "The passwords differ. Run the wizard again."; exit 1; }
  export RELEASE_KEYSTORE_PASSWORD
  ask _owner "Name to put on the certificate (yours, or the project's):"
  install -d -m 700 "$KEY_DIR"
  keytool -genkeypair -storetype PKCS12 -keystore "$KEYSTORE" \
    -storepass:env RELEASE_KEYSTORE_PASSWORD -alias release \
    -keyalg RSA -keysize 4096 -validity 10000 -dname "CN=$_owner" >/dev/null
  chmod 600 "$KEYSTORE"
  printf '  %s✓ created%s %s\n' "$GREEN" "$RESET" "$KEYSTORE"
fi
keytool -list -keystore "$KEYSTORE" -storepass:env RELEASE_KEYSTORE_PASSWORD -alias release >/dev/null \
  || { warn "That password does not open the keystore. Run the wizard again."; exit 1; }
set_secret RELEASE_KEYSTORE_BASE64 "$(base64 -w0 "$KEYSTORE")"
set_secret RELEASE_KEYSTORE_PASSWORD "$RELEASE_KEYSTORE_PASSWORD"
set_secret RELEASE_KEY_ALIAS release
warn "Back up $KEYSTORE and its password somewhere off this machine."
warn "If both are lost, nobody can update the app without uninstalling it first."
pause

# ── Stage 2: let release-please open its pull request ─────────────────────
stage "GitHub Actions permissions"
say "release-please keeps a release pull request open on main."
say "GitHub blocks workflows from opening pull requests until you allow it."
if confirm "Allow GitHub Actions to create pull requests in $REPO?"; then
  gh api -X PUT "repos/$REPO/actions/permissions/workflow" \
    -f default_workflow_permissions=read -F can_approve_pull_request_reviews=true >/dev/null \
    && printf '  %s✓ allowed%s\n' "$GREEN" "$RESET" \
    || SKIPPED+=("Settings > Actions > General > Allow GitHub Actions to create and approve pull requests")
else
  SKIPPED+=("Settings > Actions > General > Allow GitHub Actions to create and approve pull requests")
fi
pause

# ── Stage 3: one conventional commit per pull request ─────────────────────
stage "Squash merging"
say "release-please reads commit subjects such as 'feat: ...' and 'fix: ...' on main."
say "With squash merging the pull request title becomes that subject, and CI checks the title."
if confirm "Make squash the only merge method, using the PR title as the commit subject?"; then
  gh api -X PATCH "repos/$REPO" -F allow_squash_merge=true -F allow_merge_commit=false \
    -F allow_rebase_merge=false -F delete_branch_on_merge=true \
    -f squash_merge_commit_title=PR_TITLE -f squash_merge_commit_message=PR_BODY >/dev/null \
    && printf '  %s✓ squash merging only%s\n' "$GREEN" "$RESET" \
    || SKIPPED+=("Settings > General > Pull Requests > allow squash merging only")
else
  SKIPPED+=("Settings > General > Pull Requests > allow squash merging only")
fi
pause

# ── Stage 4: publishing the daemon to the AUR ─────────────────────────────
stage "AUR package (optional)"
say "Each release can push packaging/aur/PKGBUILD to the AUR as the 'varchd' package."
say "Skip this and releases still ship the APK and the daemon tarballs."
if confirm "Set up AUR publishing now?"; then
  open_url "https://aur.archlinux.org/register"
  step "Create an AUR account, or log in if you already have one."
  ask AUR_USERNAME "Your AUR username:"
  ask AUR_EMAIL "Email for AUR commits (public, so a noreply address is fine):"
  if [[ ! -f "$AUR_KEY" ]]; then
    ssh-keygen -q -t ed25519 -N "" -C "varchd release pipeline" -f "$AUR_KEY"
    printf '  %s✓ created%s %s\n' "$GREEN" "$RESET" "$AUR_KEY"
  fi
  open_url "https://aur.archlinux.org/account/$AUR_USERNAME/edit"
  step "On the account page, paste this line into 'SSH Public Key':"
  printf '\n    %s\n\n' "$(cat "$AUR_KEY.pub")"
  step "Enter your AUR password at the bottom of the page and press Update."
  pause "Press Enter once the key is saved"
  set_secret AUR_SSH_PRIVATE_KEY "$(cat "$AUR_KEY")"
  set_var AUR_USERNAME "$AUR_USERNAME"
  set_var AUR_EMAIL "$AUR_EMAIL"
  set_var AUR_PUBLISH true
  note "The first release creates the 'varchd' package on the AUR."
  pause
else
  note "Run this wizard again whenever you want to turn it on."
  pause
fi

finish
